<a href="https://colab.research.google.com/github/rfaoktvian/AnalisisSentimenDebatCapres2024/blob/main/Analisis_Sentiman_Youtube_Debat_Capres_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv('youtube_comments_debat_capres2024.csv')
df.head(100)

comment_text  like_count  \
0   Menjatuhkan kinerja seseorg dipublik sama dgñ ...           1   
1       Aku terbangun jam 2 mlm tiba2 ingat debat ini           1   
2                      this year everything is proven           2   
3   gua balik lagi kesini, gara gara konoha mulai ...          12   
4   Hanya Pak Anis yg bahas isu lingkungan di deba...           4   
..                                                ...         ...   
95                             Kayak nyari" kesalahan           0   
96  Ini Anis parah banget terlalu menyerang pribad...           0   
97  Flash back liat debat presiden ini\n01 & 03 pr...           0   
98  Ini Anis ngapain nanyak pribadi ya ,kampret bnget           0   
99  Semangat pak prabowo, makasih udah berjuang sa...           3   

    reply_count          published_at  
0             0  2026-01-21T17:42:14Z  
1             0  2026-01-15T19:17:31Z  
2             0  2026-01-14T05:12:17Z  
3             2  2025-12-20T16:19:49Z  
4             0  2025-12-14T12:47:20Z  
..          ...                   ...  
95            0  2024-02-17T14:35:40Z  
96            0  2024-02-17T14:30:53Z  
97            0  2024-02-17T14:28:24Z  
98            0  2024-02-17T12:30:33Z  
99            0  2024-02-17T11:35:12Z  

[100 rows x 4 columns]

In [52]:
df['reply_count'].value_counts()

reply_count
0      9824
1       580
2       151
3        71
4        37
       ... 
155       1
67        1
91        1
23        1
112       1
Name: count, Length: 66, dtype: int64

In [53]:
df.shape

(10930, 4)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10930 entries, 0 to 10929
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   comment_text  10930 non-null  object
 1   like_count    10930 non-null  int64 
 2   reply_count   10930 non-null  int64 
 3   published_at  10930 non-null  object
dtypes: int64(2), object(2)
memory usage: 341.7+ KB


In [55]:
df.duplicated().sum()

np.int64(9)

In [56]:
# duplicated handling
clean_df = df.drop_duplicates()

In [57]:
clean_df.duplicated().sum()

np.int64(0)

In [58]:
clean_df.shape

(10921, 4)

In [59]:
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def cleaningText(text):
    text = re.sub(r'@[A-Za-z0-9]+', '', text) # menghapus mention
    text = re.sub(r'#[A-Za-z0-9]+', '', text) # menghapus hashtag
    text = re.sub(r'RT[\s]', '', text) # menghapus RT
    text = re.sub(r"http\S+", '', text) # menghapus link
    text = re.sub(r'[0-9]+', '', text) # menghapus angka
    text = re.sub(r'[^\w\s]', '', text) # menghapus karakter selain huruf dan angka

    text = text.replace('\n', ' ') # mengganti baris baru dengan spasi
    text = text.strip(' ') # menghapus karakter spasi dari kiri dan kanan teks
    return text

slangwords = {
    "abis": "habis",
    "bgt": "banget",
    "bangettt": "banget",
    "bgtt": "banget",
    "gk": "tidak",
    "ga": "tidak",
    "gak": "tidak",
    "nggak": "tidak",
    "enggak": "tidak",
    "tdk": "tidak",
    "dr": "dari",
    "dri": "dari",
    "aja": "saja",
    "udh": "sudah",
    "udah": "sudah",
    "blm": "belum",
    "belom": "belum",
    "pdhl": "padahal",
    "krn": "karena",
    "sm": "sama",
    "jg": "juga",
    "tp": "tapi",
    "trs": "terus",
    "org": "orang",
    "kmrn": "kemarin",
    "skrg": "sekarang",
    "omon": "bicara",
    "sory": "sorry",
    "sori": "sorry",
    "anis": "anies",
    "kren": "keren",
    "sy": "saya",
    "sya": "saya",
    "nnti": "nanti"
}

def fix_slangwords(text):
    words = text.split()
    fixed_words = []

    for word in words:
        if word in slangwords:
            fixed_words.append(slangwords[word])
        else:
            fixed_words.append(word)

    return " ".join(fixed_words)


def casefoldingText(text): # Mengubah semua karakter dalam teks menjadi huruf kecil
    text = text.lower()
    return text

def tokenizingText(text): # Memecah atau membagi string, teks menjadi daftar token
    text = word_tokenize(text)
    return text

def filteringText(tokens):
    stop_id = set(stopwords.words('indonesian'))
    stop_en = set(stopwords.words('english'))

    negation_words = {"tidak", "bukan", "jangan", "nggak", "enggak"}

    stopwords_all = (stop_id | stop_en) - negation_words

    custom_stopwords = {
        "iya","yaa","sih","loh","kah","woi","woii","woy",
        "nya","ku","di","ke","dari"
    }

    stopwords_all.update(custom_stopwords)

    return [word for word in tokens if word not in stopwords_all]

def toSentence(list_words): # Mengubah daftar kata menjadi kalimat
    sentence = ' '.join(word for word in list_words)
    return sentence

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemmingText(text):
    return stemmer.stem(text)



In [42]:
import nltk
nltk.download('punkt_tab')
nltk.download('stopwords')

clean_df["clean"] = clean_df["comment_text"].apply(cleaningText)
clean_df["lower"] = clean_df["clean"].apply(casefoldingText)
clean_df["slang"] = clean_df["lower"].apply(fix_slangwords)
clean_df["token"] = clean_df["slang"].apply(tokenizingText)
clean_df["filtered"] = clean_df["token"].apply(filteringText)
clean_df["sentence"] = clean_df["filtered"].apply(toSentence)
clean_df["final_text"] = clean_df["sentence"].apply(stemmingText)


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/tmp/ipython-input-293603581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df["clean"] = clean_df["comment_text"].apply(cleaningText)
/tmp/ipython-input-293603581.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df["lower"] = clean_df["clean"].apply(cas

In [43]:
import requests
from io import StringIO


lexicon_positive = dict()

response = requests.get('https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_positive.csv')


if response.status_code == 200:
    reader = csv.reader(StringIO(response.text), delimiter=',')

    for row in reader:
        lexicon_positive[row[0]] = int(row[1])
else:
    print("Failed to fetch positive lexicon data")

lexicon_negative = dict()

response = requests.get('https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_negative.csv')

if response.status_code == 200:
    reader = csv.reader(StringIO(response.text), delimiter=',')
    for row in reader:
        lexicon_negative[row[0]] = int(row[1])
else:
    print("Failed to fetch negative lexicon data")

In [44]:
def sentiment_analysis_lexicon_indonesia(text):
    score = 0

    for word in text.split():
        if word in lexicon_positive:
            score += lexicon_positive[word]
        elif word in lexicon_negative:
            score += lexicon_negative[word]

    if score > 0:
        polarity = "positive"
    elif score < 0:
        polarity = "negative"
    else:
        polarity = "neutral"

    return score, polarity


In [45]:
results = clean_df['final_text'].apply(sentiment_analysis_lexicon_indonesia)
results = list(zip(*results))
clean_df['polarity_score'] = results[0]
clean_df['polarity'] = results[1]

/tmp/ipython-input-2166883952.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['polarity_score'] = results[0]
/tmp/ipython-input-2166883952.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['polarity'] = results[1]


In [46]:
print(clean_df['polarity'].value_counts())
print(clean_df['polarity'].value_counts(normalize=True))


polarity
positive    5668
negative    3058
neutral     2195
Name: count, dtype: int64
polarity
positive    0.519000
negative    0.280011
neutral     0.200989
Name: proportion, dtype: float64


In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

X = clean_df['final_text']
y = clean_df['polarity']

tfidf = TfidfVectorizer(
    max_features=3000,
    min_df=5,
    max_df=0.9,
    ngram_range=(1, 2)
)

X_tfidf = tfidf.fit_transform(X)

features_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [48]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

model.fit(X_train, y_train)


LogisticRegression(class_weight='balanced', max_iter=1000)

In [49]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

    negative       0.78      0.78      0.78       612
     neutral       0.66      0.87      0.75       439
    positive       0.93      0.81      0.87      1134

    accuracy                           0.82      2185
   macro avg       0.79      0.82      0.80      2185
weighted avg       0.83      0.82      0.82      2185

[[479  88  45]
 [ 31 382  26]
 [101 111 922]]


In [50]:
# Jalankan ini di satu cell Colab
with open('requirements.txt', 'w') as f:
    f.write('google-api-python-client\n')
    f.write('pandas\n')
    f.write('numpy\n')
    f.write('matplotlib\n')
    f.write('scikit-learn\n')
    f.write('tensorflow\n')
    f.write('nltk\n')
    f.write('sastrawi\n')
    f.write('requests\n')